// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB3UaR3xQDoPmU6Q4rINfVUMjAHqIqm5g',
    appId: '1:51248346812:web:cf5d394b8ac600d02c42b9',
    messagingSenderId: '51248346812',
    projectId: 'bola-de-ouro-1',
    authDomain: 'bola-de-ouro-1.firebaseapp.com',
    storageBucket: 'bola-de-ouro-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhWYS7sCFlOiiyyOC96qXcUfA9N-8pL7I',
    appId: '1:51248346812:android:704af31cd5c929f72c42b9',
    messagingSenderId: '51248346812',
    projectId: 'bola-de-ouro-1',
    storageBucket: 'bola-de-ouro-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4OW3jgUeb-RQojGv1dijYuT-WN_XHnbE',
    appId: '1:51248346812:ios:e5170fe9735b4b072c42b9',
    messagingSenderId: '51248346812',
    projectId: 'bola-de-ouro-1',
    storageBucket: 'bola-de-ouro-1.appspot.com',
    iosClientId: '51248346812-rkk2acf0gdcckdiu7skre4f6b5qgflnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.bolaDeOuro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4OW3jgUeb-RQojGv1dijYuT-WN_XHnbE',
    appId: '1:51248346812:ios:e5170fe9735b4b072c42b9',
    messagingSenderId: '51248346812',
    projectId: 'bola-de-ouro-1',
    storageBucket: 'bola-de-ouro-1.appspot.com',
    iosClientId: '51248346812-rkk2acf0gdcckdiu7skre4f6b5qgflnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.bolaDeOuro',
  );
}
